spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: password
  jpa: database-platform=org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true

---

spring:
  profiles: dev
  datasource:
    username: db
    password: db
    url: jdbc:postgresql://localhost:5432/postgres_demo
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
